export type GameDefinition = {
  id: string;
  title: string;
  symbol: string;
  category: string;
  tagline: string;
  duration: string;
  playable: boolean;
  instructions: string[];
};

export const GAMES: GameDefinition[] = [
  { id:'lights-out', title:'Lights Out', symbol:'🏎️', category:'REACTION', tagline:'Five starts. React the instant the lights go out.', duration:'5 starts', playable:true, instructions:['Wait for all five red lights.','Tap the reaction pad the instant the lights go out.','A tap before lights-out is a false start.','Lowest median reaction time wins.'] },
  { id:'time-stop', title:'Time Stop', symbol:'⏱️', category:'INTERNAL TIMING', tagline:'Stop an invisible clock closest to the target time.', duration:'3 targets', playable:true, instructions:['You receive three random target times under 15 seconds.','Each target begins automatically after a 3-second countdown — there is no Ready button.','The clock is visible for the first second, then disappears.','Tap STOP when you think the target time has elapsed. If you do not stop within 20 seconds, that target times out automatically.','Lowest total absolute error wins.'] },
  { id:'shrink-ring', title:'Shrink Ring', symbol:'🎯', category:'PRECISION', tagline:'Stop three sweeping rings as the target zone shrinks.', duration:'3 rings', playable:true, instructions:['Tap STOP while the sweeping needle is inside the green zone.','Score up to 100 points per ring based on distance from the centre.',"A successful hit shrinks the next ring\'s green zone.",'You have 8 seconds per ring. Highest total score wins.'] },
  { id:'parry', title:'Parry', symbol:'⚔️', category:'REACTION + CONTROL', tagline:'Read the tell, ignore the feint, parry the real strike.', duration:'10 encounters', playable:true, instructions:['Watch the sword during the wind-up. Do not rely on the text panel — it stays neutral.','Tap PARRY only when the sword commits to a genuine strike. Faster reactions score more, but slower successful parries still earn points.','Some wind-ups are feints. Ignore the entire fake attack — any tap during the feint scores 0 points.','10 encounters · 100 points each · highest total wins.'] },
  { id:'blind-beat', title:'Blind Beat', symbol:'🥁', category:'RHYTHM + MEMORY', tagline:'Lock onto the pulse, then keep it when the cue disappears.', duration:'8 bars', playable:true, instructions:['Follow and tap with the visible metronome for 4 bars.','Then the visual cue disappears for another 4 bars. Keep tapping at the same tempo.','Each blind tap is matched to the hidden beat sequence. Your score is your average timing error in milliseconds.','A missed beat costs 750 ms and an extra tap costs 300 ms. Lowest average error wins.'] },
  { id:'overpour', title:'Overpour', symbol:'🥤', category:'HOLD + RELEASE', tagline:'Hold to pour, then release as close as possible to the target line.', duration:'5 pours', playable:true, instructions:['Each round shows a new target fill line and pour speed.','Press and HOLD the POUR button to fill the glass, then release near the target line.','Small underpours and overpours still score well; points fall smoothly with distance from the line.','5 pours · 100 points each · highest total wins. Rounds advance automatically if you do nothing or overflow.'] },
  { id:'charge-shot', title:'Charge Shot', symbol:'🚀', category:'HOLD + RELEASE', tagline:'Charge the launcher, release, and land as close as possible to the target.', duration:'5 shots', playable:true, instructions:['Press and hold CHARGE to build launch power, then release to fire.','Each shot has a new target position and launcher strength, shared by both opponents.','Landing close to the centre scores up to 100 points. Small misses still score; large misses score less.','5 shots · 500 points maximum · highest total wins. If you do nothing or reach full charge, the shot advances automatically.'] },
  { id:'stack', title:'Stack', symbol:'🧱', category:'SPATIAL PRECISION', tagline:'Drop moving blocks, slice the overhang, and keep the tower alive.', duration:'8 drops', playable:true, instructions:['A block sweeps left and right above the tower. Tap DROP BLOCK to place it.','Every new block moves faster, so the timing gets harder as the tower grows.','Any overhang is sliced away, so the next block becomes narrower. Near-perfect alignment can snap cleanly for 100 points.','8 drops · 100 points each · 800 maximum. Highest total wins. Each drop times out automatically after 6 seconds.'] },
  { id:'trace', title:'Trace', symbol:'✏️', category:'SPATIAL PRECISION', tagline:'Trace accurately, then use speed to separate the best runs.', duration:'3 paths', playable:true, instructions:['Press and hold on START, then drag along the glowing path to FINISH.','Accuracy remains the main score: small wobbles score well, larger deviations reduce the base score.','Speed then applies an 85–100% multiplier: complete the path faster without sacrificing accuracy for the best result.','The full route is sampled, so cutting straight across the path will score poorly. 3 paths · 100 points each · 300 maximum.'] },
  { id:'ricochet', title:'One Shot Ricochet', symbol:'💥', category:'ANGLE + PREDICTION', tagline:'One shot. Time the moving launcher and bank around the shield into the bullseye.', duration:'1 shot', playable:true, instructions:['Drag inside the arena to aim. The arrow shows the exact initial direction of the shot, but not the future bounce path.','The launcher moves vertically while you aim, so choose both the bank angle and the right moment to fire.','The shield blocks the direct route. Bank off the top or bottom wall and finish as close as possible to the bullseye.','You have 12 seconds to aim; if time expires, the current angle and launcher height fire automatically. Highest score wins.'] },
  { id:'knife-wheel', title:'Knife Wheel', symbol:'🔪', category:'TIMING + SPACE', tagline:'Time each throw and thread knives into the shrinking gaps.', duration:'10 throws', playable:true, instructions:['Watch the spinning wheel and tap THROW KNIFE when the bottom contact point lines up with a safe gap.','Successful knives stay embedded, so the available gaps shrink as the round continues.','A collision scores 0 for that throw but does not end the match. Clean, centred gap placements score up to 100 points.','10 throws · 1000 points maximum · highest total wins. Each throw advances automatically if you do nothing.'] },
  { id:'conveyor-chef', title:'Conveyor Chef', symbol:'👨‍🍳', category:'TRACKING', tagline:'Cut moving ingredients exactly on their marked line.', duration:'Coming soon', playable:false, instructions:['Track the moving cut line.','Tap when it reaches the knife.'] },
  { id:'pole-balance', title:'Pole Balance', symbol:'🤹', category:'MICRO-CONTROL', tagline:'Balance the pole while walking it to the marker.', duration:'Coming soon', playable:false, instructions:['Use tiny corrections.','Overcorrection creates momentum.'] },
];

export const GAME_BY_ID = new Map(GAMES.map(game => [game.id, game]));
export const PLAYABLE_GAMES = GAMES.filter(game => game.playable);
